# For image-based datasets like MNIST
_target_: torch.nn.Sequential
_args_:
  - _target_: torch.nn.Linear
    in_features: ${sum:${experiment.latent_dim},${experiment.latent_dim}}
    out_features: 512
  - _target_: torch.nn.ReLU
  - _target_: torch.nn.Linear
    in_features: 512
    out_features: 512
  - _target_: torch.nn.ReLU
  - _target_: torch.nn.Linear
    in_features: 512
    out_features: 784
  - _target_: torch.nn.Sigmoid
  - _target_: torch.nn.Unflatten
    dim: -1
    unflattened_size: [1, 28, 28] 