# @package _global_.model
_target_: model.cnnvae_large.CNNVAELarge
in_channels: ${dataset.data_shape[0]}
n_feat: 384
latent_dim: ${experiment.latent_dim}
vae_latent_dim: 256 # Can be tuned
image_size: ${dataset.data_shape[1]} # Should ideally be 64 or larger for this architecture 