_target_: generator.ddpm.DDPM
model: ${experiment.model}  # This will be instantiated first
betas: [1e-4, 0.02]
n_T: 400
drop_prob: 0.1 
noise_shape: ${experiment.dataset.data_shape}
subsample_indices: 1000