# @package _global_.generator
_target_ : generator.protein_generator.Progen2Generator
progen2_name: 'hugohrban/progen2-medium'
latent_dim: ${experiment.latent_dim}
prefix_length: 10
max_length: 512
temperature: 1.0