# A scheduler that does nothing (keeps learning rate constant)
_target_: torch.optim.lr_scheduler.ConstantLR
_partial_: true
factor: 1.0
total_iters: 1  # Only runs for 1 iteration, then stays constant