# @package _global_.encoder
_target_: encoder.nlp_encoders.DocumentSetEncoder
bert_model_name: ${experiment.bert_model_name}
bert_output_dim: ${experiment.bert_output_dim}
latent_dim: ${experiment.latent_dim}
hidden_dim: ${experiment.hidden_dim}
pooling_strategy: ${experiment.pooling_strategy}
freeze_bert: ${experiment.freeze_bert}
distribution_encoder_type: ${experiment.distribution_encoder_type}
distribution_layers: ${experiment.distribution_layers}