# @package _global_.encoder
_target_: encoder.protein_encoders.ProteinSetEncoder
esm_model_name: 'facebook/esm2_t6_8M_UR50D'
latent_dim: ${experiment.latent_dim}
hidden_dim: ${experiment.hidden_dim}
pooling: 'mean'
freeze: false
dist_type: 'tx'
layers: 2
heads: 4