# @package _global_.encoder
_target_: encoder.perturbseq_encoders.DistributionEncoderResNetPertPredictor
in_dim: ${dataset.data_shape[0]}
latent_dim: ${experiment.latent_dim}
hidden_dim: ${experiment.hidden_dim}
set_size: ${experiment.set_size}
pert_embedding_dim: ${experiment.pert_embedding_dim}
layers: 2
fc_layers: 2 