_target_: encoder.encoders.DistributionEncoderResNetTx
in_dim: ${experiment.dataset.data_shape[0]}
latent_dim: ${experiment.latent_dim}
hidden_dim: ${experiment.hidden_dim}
set_size: ${experiment.set_size}
layers: 2
fc_layers: 2 
norm: true
heads: 4