# @package _global_

# Set default configurations
defaults:
  - dataset: dna
  - encoder: dna_conv
  - generator: hyenadna
  - optimizer: adam
  - scheduler: cosine
  - training: default
  - wandb: default
  - mixer: none
  - _self_

experiment:
  latent_dim: 32
  name: dna_hyena
  set_size: 20
  batch_size: 8

# Optimizer settings
optimizer:
  lr: 1e-4
  weight_decay: 1e-5

# General settings
seed: 42
device: cuda
experiment_name: dna_distribution_embeddings

# Hydra-related settings
hydra:
  run:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    config:
      override_dirname:
        exclude_keys:
          - seed
          - device
          - hydra
          - experiment_name 