# @package _global_

# Set default configurations
defaults:
  - dataset: essential_genes
  - encoder: gnn
  - model: direct_mlp
  - generator: wasserstein
  - optimizer: adam
  - scheduler: cosine
  - training: default
  - wandb: default
  - _self_

experiment:
  latent_dim: 128  # Increased from 16 for potentially more complex data
  hidden_dim: 1024 # Increased from 64 for more capacity
  noise_dim: 64
  set_size: 100
  batch_size: 256
  lr: 2e-4

# General settings
seed: 42
device: cuda
experiment_name: essential_genes

# Hydra-related settings
hydra:
  run:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    config:
      override_dirname:
        exclude_keys:
          - seed
          - device
          - hydra
          - experiment_name 