# @package _global_

# Set default configurations
defaults:
  - dataset: mnist_bernoulli
  - encoder: conv_gnn  # Use the ConvDistributionEncoder for DDPM
  - model: context_unet  # Use the context_unet model for DDPM
  - generator: ddpm  # Use the DDPM generator
  - optimizer: adam
  - scheduler: none
  - training: default
  - wandb: default
  - override hydra/launcher: slurm
  - _self_

experiment:
  name: mnist_bernoulli
  latent_dim: 16  # Dimension of latent space for the distribution encoder
  hidden_dim: 64  # Hidden dimension for neural networks
  noise_dim: 16  # Noise dimension for generation
  set_size: 100  # Size of each set of MNIST digits
  batch_size: 8  # Batch size for training
  lr: 1e-4  # Learning rate

# General settings
seed: 42
device: cuda
experiment_name: mnist_bernoulli

# Hydra-related settings
hydra:
  run:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    config:
      override_dirname:
        exclude_keys:
          - seed
          - device
          - hydra
          - experiment_name 