# @package _global_

# Set default configurations
defaults:
  - dataset: ranked_normal
  - encoder: tx
  - model: direct_mlp
  - generator: wasserstein
  - optimizer: adam
  - scheduler: none
  - training: fast
  - wandb: default
  - _self_

experiment:
  latent_dim: 16
  hidden_dim: 64
  noise_dim: 16
  set_size: 100
  batch_size: 64
  lr: 2e-4

# General settings
seed: 42
device: cuda
experiment_name: cov_rank

# Hydra-related settings
hydra:
  run:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    config:
      override_dirname:
        exclude_keys:
          - seed
          - device
          - hydra
          - experiment_name 