# @package _global_.dataset
_target_: datasets.distribution_datasets.GaussianMixtureModelDataset
n_sets: 10000
set_size: 1000
data_shape: [2]
seed: ${seed} 
n_components: 3
prior_mu: [0, 5]
prior_cov_df: 10
prior_cov_scale: 1
dirichlet_alpha: 1
