# @package _global_.dataset
_target_: datasets.gpra_dna_dataset.GPRADNADataset

# Data location and processing parameters
data_dir: "/orcd/data/omarabu/001/njwfish/DistributionEmbeddings/data/gpra_processed"
set_size: ${experiment.set_size}  # Number of sequences per set (from experiment config)
num_quantiles: 100  # Number of quantiles to divide expression values
window_width: 3  # Width of sliding window for selecting sequences

# Sequence parameters
max_seq_length: 129  # Maximum sequence length for both encoder and HyenaDNA

# Tokenizers
encoder_tokenizer: "dna"  # Tokenizer type for the encoder ("dna" for one-hot encoding)
hyena_tokenizer: "char"  # Tokenizer type for HyenaDNA

# Auto-calculation of sets
num_sets: 100000  # If null/None, sets are calculated to cover all sequences

# Reproducibility
seed: ${seed}  # Inherit from global seed 