_target_: datasets.mnist.MNISTMixedSetsDataset
n_sets: 10000
set_size: 100
classes_per_set: 2
root: /orcd/data/omarabu/001/njwfish/DistributionEmbeddings/data
train: true
download: true
seed: ${seed} 
data_shape: [1, 28, 28]