# @package _global_.dataset
_target_: datasets.distribution_datasets.MultivariateNormalDistributionDataset
n_sets: 50000
set_size: ${experiment.set_size}
data_shape: [5]
seed: ${seed} 
prior_mu: [0, 5]
prior_cov_df: 10
prior_cov_scale: 1
