# @package _global_.dataset
_target_: datasets.synthetic_protein.SyntheticProteinDataset

# Basic parameters
num_sets: 100           # Number of different motif sets to generate
set_size: ${experiment.set_size}  # Number of sequences per set (from experiment config)
pattern_length: 4      # Length of the repeating motif
seq_length: 10         # Length of each sequence

# Advanced parameters
num_patterns_per_set: 1  # Number of different patterns within a set (usually 1 for simplicity)
amino_acids: ["A", "C", "D", "E", "F", "G", "H", "I", "K", "L", "M", "N", "P", "Q", "R", "S", "T", "V", "W", "Y"]
mutation_rate: 0.05      # Rate at which to mutate amino acids
max_seq_length: 12      # Maximum sequence length

# Model names for tokenization
esm_name: ${experiment.esm_model_name}       # ESM model for encoder
progen_name: ${experiment.progen2_model_name}     # Progen model for generator

# Reproducibility
seed: ${seed}  # Inherit from global seed 